stages:
  - deploy

deploy to staging:
  stage: deploy
  script: 
    - npm i --prefix ./static
    - npm run build --prefix ./static
    - npm i --prefix ./server
    - npm run build --prefix ./server
  only:
    - master

deploy to production:
  stage: deploy
  script: 
    - npm i --prefix ./static
    - npm run produce --prefix ./static
    - npm i --prefix ./server
    - npm run build --prefix ./server
  environment:
    name: production
  only:
    - tags
